# Deprecated bindings file. New installations include everything directly.

bindd = SUPER, RETURN, Terminal, exec, $terminal
bindd = SUPER CTRL, F, File manager, exec, $fileManager

bindd = SUPER, B, Web browser, exec, vivaldi
bindd = SUPER, Y, Toggle VPN connection, exec, pkill -USR1 -f AmneziaVPN
bindd = SUPER, O, Obsidian, exec, obsidian -disable-gpu

bindd = SUPER, L, CLion, exec, clion


source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
