# Menus
bindd = SUPER, RETURN, Launch apps, exec, omarchy-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, omarchy-launch-walker -m symbols
bindd = SUPER ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER, ESCAPE, System menu, exec, omarchy-menu system
bindld = , XF86PowerOff, Power menu, exec, omarchy-menu system
# bindd = SUPER, K, Show key bindings, exec, omarchy-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER, D, Toggle top bar, exec, omarchy-toggle-waybar
# bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, omarchy-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle workspace gaps, exec, omarchy-hyprland-workspace-toggle-gaps

# Sleep
bindd = SUPER, U, Sleep, exec, systemctl suspend

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, makoctl mode -t do-not-disturb && makoctl mode | grep -q 'do-not-disturb' && notify-send "Silenced notifications" || notify-send "Enabled notifications"
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggle idling
bindd = SUPER CTRL, I, Toggle locking on idle, exec, omarchy-toggle-idle

# Toggle nightlight
# bindd = SUPER CTRL, N, Toggle nightlight, exec, omarchy-toggle-nightlight

bindd = SUPER, Q, Screenshot, exec, omarchy-cmd-screenshot
bindd = SUPER SHIFT, Q, Screenrecording, exec, omarchy-menu screenrecord
#
# File sharing
bindd = SUPER CTRL, S, Share, exec, omarchy-menu share

# bindd = SUPER, V, Show time, exec, notify-send "$(date +'%H:%M  %d.%m.%y  %a' | tr '[:upper:]' '[:lower:]')" --expire-time=600 --urgency=low --transient
# bindd = SUPER, C, Show battery remaining, exec, notify-send "$(omarchy-battery-remaining)%" --expire-time=370 --urgency=low --transient
bindd = ALT, SPACE, Show workspace, exec, notify-send "$(hyprctl activeworkspace | grep 'workspace ID' | awk '{print $3}')" --expire-time=240 --urgency=low --transient

bindd = ALT, A, VPN, exec, adguardvpn-cli connect --fastest
bindd = SUPER, R, AmneziaVPN, exec, AmneziaVPN

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, omarchy-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, omarchy-launch-bluetooth
bindd = SUPER, W, Wifi controls, exec, omarchy-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, omarchy-launch-tui btop

